"use client";
import { useEffect, useRef, useState } from "react";
import Script from "next/script";
import { Mic, MicOff, PhoneOff, Settings2, Play, MessageSquare, Download, Volume2, BookOpen, Upload, Headphones, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { LiveCall, type Transcript } from "@/lib/live-client";
declare global { interface Window { KPZive?: { start(c: HTMLCanvasElement, src: string): Promise<boolean>; uroven(v: number): void; stop(): void } } }
type Row = { id: number; role: "user" | "assistant"; text: string; start: number; end: number };
const labels: Record<string, string> = { idle: "Готова к разговору", connecting: "Подключаем голос и микрофон…", connected: "Говорите свободно. Клару можно перебивать.", closing: "Завершаем разговор…", reconnecting: "Восстанавливаем связь…", demo: "Приветствие из вашего видео · это запись" };
const time = (s: number) => `${String(Math.floor(s / 60)).padStart(2, "0")}:${String(Math.floor(s % 60)).padStart(2, "0")}`;
export default function Home() {
  const figure = useRef<HTMLDivElement>(null), canvas = useRef<HTMLCanvasElement>(null), call = useRef<LiveCall | null>(null), video = useRef<HTMLVideoElement>(null), list = useRef<HTMLDivElement>(null);
  const follow = useRef(true), fragments = useRef<Transcript[]>([]), rowId = useRef(0), checkMic = useRef<MediaStream | null>(null), micCtx = useRef<AudioContext | null>(null), micFrame = useRef(0);
  const [state, setState] = useState("idle"), [configured, setConfigured] = useState<boolean | null>(null), [settings, setSettings] = useState(false), [knowledge, setKnowledge] = useState("");
  const [rows, setRows] = useState<Row[]>([]), [error, setError] = useState(""), [muted, setMuted] = useState(false), [input, setInput] = useState(0), [output, setOutput] = useState(0);
  const [elapsed, setElapsed] = useState(0), [tokens, setTokens] = useState<number | null>(null), [usageSeconds, setUsageSeconds] = useState<number | null>(null), [finalUsage, setFinalUsage] = useState(false), [blocked, setBlocked] = useState(false), [micTest, setMicTest] = useState(false);
  const active = ["connecting", "connected", "closing", "reconnecting"].includes(state);
  const statusCheck = async () => { try { const r = await fetch("/api/session", { cache: "no-store" }); if (!r.ok) throw new Error(); const d = await r.json() as { configured: boolean }; setConfigured(d.configured); return Boolean(d.configured); } catch { setConfigured(null); setError("Не удалось проверить подключение. Обновите страницу."); return false; } };
  const startAvatar = () => { if (canvas.current) void window.KPZive?.start(canvas.current, "/klara.webp").then(ok => { if (!ok) setError("Не удалось загрузить изображение Клары."); }); };
  const stopMic = () => { cancelAnimationFrame(micFrame.current); checkMic.current?.getTracks().forEach(t => t.stop()); checkMic.current = null; void micCtx.current?.close().catch(() => {}); micCtx.current = null; setMicTest(false); setInput(0); };
  useEffect(() => { void statusCheck(); const leave = () => { call.current?.stop(); call.current?.dispose(); checkMic.current?.getTracks().forEach(t => t.stop()); }; window.addEventListener("pagehide", leave); return () => { leave(); window.KPZive?.stop(); cancelAnimationFrame(micFrame.current); void micCtx.current?.close().catch(() => {}); window.removeEventListener("pagehide", leave); }; }, []);
  useEffect(() => { if (state !== "connected") return; const interval = setInterval(() => setElapsed(s => s + 1), 1000); return () => clearInterval(interval); }, [state]);
  useEffect(() => { if (follow.current && list.current) list.current.scrollTop = list.current.scrollHeight; }, [rows]);
  const addFragment = (f: Transcript) => { fragments.current.push(f); setRows(prev => { const next = prev.map(r => ({ ...r })); const target = [...next].reverse().find(r => r.role === f.role && f.start_ms >= r.start && f.start_ms - r.end < 1600); if (target) { target.text += f.delta; target.end = Math.max(target.end, f.end_ms); } else next.push({ id: ++rowId.current, role: f.role, text: f.delta, start: f.start_ms, end: f.end_ms }); return next; }); };
  const start = async () => {
    if (active) return; setError(""); stopMic(); video.current?.pause(); setState("connecting");
    const ready = await statusCheck(); if (!ready) { setState("idle"); setSettings(true); return; }
    setRows([]); fragments.current = []; rowId.current = 0; setElapsed(0); setTokens(null); setUsageSeconds(null); setFinalUsage(false); setMuted(false); setBlocked(false);
    const current = new LiveCall({ state: setState, error: setError, transcript: addFragment, playbackBlocked: setBlocked, levels: (i, o) => { setInput(i); setOutput(o); window.KPZive?.uroven(o); }, usage: (s, t, f) => { setUsageSeconds(s); setTokens(t); setFinalUsage(f); } }); call.current = current;
    try { await current.start(knowledge); } catch (e) { current.dispose(); setError(e instanceof DOMException && e.name === "NotAllowedError" ? "Разрешите доступ к микрофону в настройках браузера и попробуйте снова." : e instanceof Error ? e.message : "Не удалось начать разговор."); }
  };
  const testMicrophone = async () => { if (micTest) { stopMic(); return; } setError(""); try { const stream = await navigator.mediaDevices.getUserMedia({ audio: { echoCancellation: true } }); checkMic.current = stream; const context = new AudioContext(); micCtx.current = context; await context.resume(); const analyser = context.createAnalyser(); analyser.fftSize = 512; context.createMediaStreamSource(stream).connect(analyser); const data = new Float32Array(512); setMicTest(true); const tick = () => { analyser.getFloatTimeDomainData(data); setInput(Math.sqrt(data.reduce((s, v) => s + v * v, 0) / data.length)); micFrame.current = requestAnimationFrame(tick); }; tick(); } catch { stopMic(); setError("Микрофон недоступен. Разрешите доступ в браузере."); } };
  const demo = async () => { if (figure.current) { figure.current.classList.remove("holo-enter"); void figure.current.offsetWidth; figure.current.classList.add("holo-enter"); } stopMic(); setError(""); if (!video.current) return; video.current.currentTime = 0; setState("demo"); try { await video.current.play(); } catch { setState("idle"); setError("Браузер не смог воспроизвести приветствие."); } };
  const exportTranscript = () => { const blob = new Blob([JSON.stringify({ model: "gpt-live-1", recordedAt: new Date().toISOString(), elapsedSeconds: elapsed, voiceSeconds: usageSeconds, backendTokens: tokens, finalUsage, fragments: fragments.current }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "klara-conversation.json"; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  const loadKnowledge = async (file?: File) => { if (!file) return; if (file.size > 60000) { setError("Для теста загрузите небольшой текстовый файл до 60 КБ."); return; } const text = await file.text(); if (text.length > 12000) { setError("Для первого теста используйте до 12 000 символов."); return; } setKnowledge(text); };
  return <main className="shell">
    <Script src="/klara-zive.js" strategy="afterInteractive" onReady={startAvatar} />
    <header className="top"><div className="brand"><span className="brandmark">K</span><div><strong>KLÁRA</strong><div className="eyebrow">conversation lab</div></div></div><div className="top-actions"><span className="pill">GPT-Live · прототип</span><Button variant="ghost" onClick={() => setSettings(true)}><Settings2 /> Настройки</Button></div></header>
    <div className="workspace"><section aria-label="Разговор с Кларой">
      <div className="stage"><div className="stage-head"><div><h1>Давай поговорим.</h1><p>{state === "connected" ? (output > .025 ? "Клара говорит" : muted ? "Микрофон выключен" : "Клара слушает") : "Твоя Клара. Живой голос."}</p></div><span className="pill">{time(elapsed)}</span></div>
        <svg width="0" height="0" aria-hidden="true" className="holo-def"><defs><filter id="klaraLuma" colorInterpolationFilters="sRGB"><feColorMatrix type="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  .299 .587 .114 0 0" /><feComponentTransfer><feFuncA type="gamma" amplitude="1.6" exponent="0.8" offset="-0.2" /></feComponentTransfer></filter></defs></svg>
        <div className="avatar-wrap"><div ref={figure} className={`holo-figure holo-enter${state === "demo" ? " greeting" : ""}`}><canvas ref={canvas} aria-label="Анимированный аватар Клары"  />
        <video ref={video} src="/klara-uvitani.mp4" playsInline preload="metadata" className="intro-video"  onEnded={() => setState("idle")} /></div></div>
        <div className="stage-foot">{state === "demo" ? "Записанное приветствие · HeyGen" : "Синтетический голос · анимация губ по звуку"}</div>
      </div>
      <div className="talk-controls"><Button variant="outline" size="icon" aria-label={muted ? "Включить микрофон" : "Выключить микрофон"} disabled={state !== "connected"} onClick={() => { call.current?.mute(!muted); setMuted(!muted); }}>{muted ? <MicOff /> : <Mic />}</Button>
        <Button className="main-call" variant={active ? "destructive" : "default"} disabled={state === "closing" || state === "connecting"} onClick={active ? () => call.current?.stop() : start}>{state === "connecting" || state === "closing" ? <Loader2 className="animate-spin" /> : active ? <PhoneOff /> : <Mic />}{active ? state === "connecting" ? "Подключение" : "Завершить" : "Начать разговор"}</Button>
        <Button variant="outline" size="icon" aria-label={state === "demo" ? "Остановить приветствие" : "Послушать записанное приветствие"} disabled={active} onClick={state === "demo" ? () => { video.current?.pause(); setState("idle"); } : demo}>{state === "demo" ? <PhoneOff /> : <Play />}</Button>
      </div><p className="status-line" role="status">{labels[state]}</p>
      {blocked && <Button variant="outline" onClick={() => void call.current?.play().catch(() => setError("Нажмите ещё раз, чтобы разрешить воспроизведение."))}><Volume2 /> Включить звук Клары</Button>}
      {error && <div className="error" role="alert">{error}{error.includes("OpenAI") && <p style={{ marginTop: 8 }}><a href="https://platform.openai.com/settings/organization/billing/overview" target="_blank" rel="noreferrer" style={{ textDecoration: "underline" }}>Открыть баланс OpenAI API</a></p>}</div>}
      {configured === false && <p className="note" style={{ textAlign: "center" }}>Для разговора осталось подключить API. <button onClick={() => setSettings(true)} style={{ color: "#edc28a", textDecoration: "underline" }}>Открыть настройки</button></p>}
    </section>
    <aside className="side"><div className="side-head"><h2>Разговор</h2><Button variant="ghost" size="icon" aria-label="Скачать расшифровку" disabled={!rows.length} onClick={exportTranscript}><Download /></Button></div>
      <div className="messages" ref={list} onScroll={() => { if (list.current) follow.current = list.current.scrollHeight - list.current.scrollTop - list.current.clientHeight < 70; }}>
        {rows.length ? rows.map(row => <div className={`msg ${row.role}`} key={row.id}><small>{row.role === "user" ? "ВЫ" : "КЛАРА"} · {time(row.start / 1000)}</small><p>{row.text}</p></div>) : <div className="empty"><MessageSquare size={29} strokeWidth={1.2} /><h3>Начни с «Привет»</h3><p>Спроси что-нибудь, перебей ответ, уточни вопрос. Здесь появится расшифровка вашего разговора.</p></div>}
      </div><div className="meters"><div className="meter"><span>Микрофон</span><div className="meter-track"><div className="meter-fill" style={{ width: `${Math.min(100, input * 650)}%` }} /></div></div><div className="meter"><span>Голос Клары</span><div className="meter-track"><div className="meter-fill" style={{ width: `${Math.min(100, output * 650)}%` }} /></div></div></div>
      <Button variant="ghost" disabled={active || state === "demo"} onClick={testMicrophone}><Headphones />{micTest ? "Остановить проверку" : "Проверить микрофон"}</Button>{micTest && <p className="note">Говорите: верхняя шкала должна двигаться. Звук никуда не отправляется.</p>}
      <div className="source"><div className="side-head"><h2>Знания Клары</h2><BookOpen size={19} color="#b4a17e" /></div><p>{knowledge.trim() ? `${knowledge.length.toLocaleString("ru")} символов для следующего разговора.` : "Добавь текст о своём проекте и проверь ответы по нему."}</p><Button variant="outline" onClick={() => setSettings(true)}>Добавить материалы</Button></div>
      <p className="note">Это отдельный тест. Внешняя база пока не подключена. Движение губ приблизительное, без распознавания фонем.</p>
    </aside></div>
    <footer className="footer"><span>GPT-Live · голос + материалы для теста</span><span>Голос: {usageSeconds === null ? "—" : `${usageSeconds.toFixed(1)} с`} · Токены помощника: {tokens ?? "—"} · {finalUsage ? "расход подтверждён" : "стоимость: n/a"}</span></footer>
    <Sheet open={settings} onOpenChange={setSettings}><SheetContent className="w-full sm:max-w-lg"><SheetHeader><SheetTitle>Настройки разговора</SheetTitle><SheetDescription>Подключение GPT-Live и материалы Клары.</SheetDescription></SheetHeader><div className="setup-body">
      <div className="connection"><strong>{configured ? "API-ключ подключён" : configured === false ? "Нужен API-ключ OpenAI" : "Проверяем подключение"}</strong><p>{configured ? "Доступ к самой модели проверяется при запуске разговора. Голос и работа помощника оплачиваются через API." : "Ключ хранится только на сервере. Подключите OpenAI Developers в ChatGPT, чтобы добавить ключ к этому прототипу."}</p><p><a href="https://platform.openai.com/api-keys" target="_blank" rel="noreferrer">Страница API-ключей</a> · <a href="https://platform.openai.com/settings/organization/billing/overview" target="_blank" rel="noreferrer">Баланс API</a></p><Button variant="outline" onClick={() => void statusCheck()}>Проверить подключение</Button></div>
      <div><label htmlFor="knowledge">Материалы для пробного разговора</label><Textarea id="knowledge" maxLength={12000} disabled={active} value={knowledge} onChange={e => setKnowledge(e.target.value)} placeholder="Вставь сюда факты о проекте, услуги, ответы на частые вопросы…" /><p>{knowledge.length} / 12 000 символов. Текст отправится OpenAI при старте разговора и не сохраняется после закрытия страницы.</p><Button asChild variant="outline" disabled={active}><label style={{ margin: 0, cursor: "pointer" }}><Upload /> Загрузить TXT / MD / JSON<input className="screen-reader" type="file" accept=".txt,.md,.json,text/plain" disabled={active} onChange={e => { void loadKnowledge(e.target.files?.[0]).catch(() => setError("Не удалось прочитать файл.")); e.target.value = ""; }} /></label></Button></div>
      <p>Проверка: добавь необычный факт и спроси о нём Клару. Затем спроси о том, чего в материалах нет.</p><Button onClick={() => setSettings(false)}>Готово</Button>
    </div></SheetContent></Sheet>
  </main>;
}
